format = """
$directory\
([ï‘„](white)$git_branch$git_status)\
$fill\
$kubernetes\
$docker_context\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$package\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$character\
"""

[aws]
format = "[ $symbol( $profile)( \\($region\\))]($style)"
symbol = "ó°¸"

[buf]
format = "[ $symbol( $version)]($style)"
symbol = "ï’"

[c]
format = "[ $symbol( $version)]($style)"
symbol = "î˜"

[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "

[cmd_duration]
show_milliseconds = true
format = "[ \\($duration\\)]($style)"
style = "bright-white"

[conda]
format = "[ $symbol( $environment)]($style)"
symbol = "ï„Œ"

[dart]
format = "[ $symbol( $version)]($style)"
symbol = "î˜"

[directory]
truncation_length = 3
truncate_to_repo = true
format = "[$read_only]($read_only_style)[$path ]($style)"
style = "#FF9288"
read_only = "ï€£ "
read_only_style = "#FF9288"

[docker_context]
format = "[ $symbol( $context)]($style)"
symbol = "ïŒˆ"

[elixir]
format = "[ $symbol( $version)]($style)"
symbol = "î‰µ"

[elm]
format = "[ $symbol( $version)]($style)"
symbol = "î˜¬"

[fill]
symbol = " "

[git_branch]
format = "[ $symbol $branch]($style)"
symbol = "ï˜"
style = "#FFFEC3"

[git_status]
format = "[ $conflicted$stashed$staged$deleted$untracked$ahead_behind]($style)"
conflicted = "=${count} "
ahead = "â‡¡${count} "
behind = "â‡£${count} "
diverged = "â‡¡${ahead_count}â‡£${behind_count} "
untracked = "?${count} "
stashed = "*${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "Â»${count} "
deleted = "âœ˜${count} "
style = "#82C8E2"

[golang]
format = "[ $symbol( $version)]($style)"
symbol = "î˜§"

[guix_shell]
format = "[ $symbol]($style)"
symbol = "ïŒ¥"

[haskell]
format = "[ $symbol( $version)]($style)"
symbol = "î·"

[haxe]
format = "[ $symbol( $version)]($style)"
symbol = "âŒ˜"

[hostname]
ssh_only = true
ssh_symbol = "î¬"
format = "[ $ssh_symbol( $hostname)]($style)"

[java]
format = "[ $symbol( $version)]($style)"
symbol = "î‰–"

[julia]
format = "[ $symbol( $version)]($style)"
symbol = "î˜¤"

[kotlin]
format = "[ $symbol( $version)]($style)"
symbol = "î˜´"

[lua]
format = "[ $symbol( $version)]($style)"
symbol = "î˜ "

[memory_usage]
format = "[ $symbol( $ram)]($style)"
symbol = "ï¡š"
disabled = true

[meson]
format = "[ $symbol( $project)]($style)"
symbol = "ï¨¶ "

[nim]
format = "[ $symbol( $version)]($style)"
symbol = "ïš¤"

[nix_shell]
format = "[ $symbol( $state)( \\($name\\))]($style)"
symbol = "ïŒ“"

[nodejs]
format = "[ $symbol( $version)]($style)"
symbol = "îœ˜"

[os]
disabled = true

[os.symbols]
Alpaquita = "îª¢"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "ï…»"
Arch = "ïŒƒ"
Artix = "ïŒŸ"
CentOS = "ïŒ„"
Debian = "ïŒ†"
DragonFly = "îŠ"
Emscripten = "ïˆ…"
EndeavourOS = "ï†—"
Fedora = "ïŒŠ"
FreeBSD = "ïŒŒ"
Garuda = "ï¯‘"
Gentoo = "ïŒ"
HardenedBSD = "ï²Š"
Illumos = "ïœ·"
Linux = "ïŒš"
Mabox = "î¬©"
Macos = "ïŒ‚"
Manjaro = "ïŒ’"
Mariner = "ï‡"
MidnightBSD = "ï††"
Mint = "ïŒ"
NetBSD = "ï€¤"
NixOS = "ïŒ“"
OpenBSD = "ïœ¹"
openSUSE = "ïŒ”"
OracleLinux = "ï ¶"
Pop = "ïŒª"
Raspbian = "ïŒ•"
Redhat = "ïŒ–"
RedHatEnterprise = "ïŒ–"
Redox = "ï”—"
Solus = "ï´±"
SUSE = "ïŒ”"
Ubuntu = "ïŒ›"
Unknown = "ïˆ­"
Windows = "ï¡±"

[package]
format = "[ $symbol( $version)]($style)"
symbol = "ï’‡"

[pijul_channel]
symbol = "ğŸªº"

[python]
format = "[ $symbol( $version)( \\($virtualenv\\))]($style)"
symbol = "îˆµ"

[rlang]
format = "[ $symbol( $version)]($style)"
symbol = "ï³’"

[ruby]
format = "[ $symbol( $version)]($style)"
symbol = "î‘"

[rust]
format = "[ $symbol( $version)]($style)"
symbol = "îš‹"

[scala]
format = "[ $symbol( $version)]($style)"
symbol = "îœ·"

[swift]
format = "[ $symbol( $version)]($style)"
symbol = "îš™"

[terraform]
format = "[ $symbol( $version)]($style)"
symbol = "îšš"
